# Generated by Django 3.1.4 on 2021-10-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0002_auto_20211018_1032'),
        ('user_project', '0002_auto_20211015_1134'),
    ]

    operations = [
    ]
