# Generated by Django 3.1.4 on 2021-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=50)),
                ('completed_year', models.DateField()),
                ('user_percentage', models.PositiveIntegerField()),
                ('user_CGPA', models.PositiveIntegerField()),
                ('institute_location', models.CharField(max_length=100)),
            ],
        ),
    ]
