# Generated by Django 3.1.4 on 2021-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperiance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexperiance',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userexperiance',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
