# Generated by Django 3.1.4 on 2021-10-18 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiance', '0002_auto_20211018_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperiance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
            preserve_default=False,
        ),
    ]
