# Generated by Django 3.1.4 on 2021-10-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiance', '0003_userexperiance_user'),
        ('experiance', '0002_auto_20211015_1134'),
    ]

    operations = [
    ]
